#=====================================
#Define options
#=====================================
set val(chan)           Channel/WirelessChannel    ;#Channel Type
set val(prop)           Propagation/TwoRayGround   ;# radio-propagation model
set val(netif)          Phy/WirelessPhy            ;# network interface type
set val(mac)            Mac/802_11                 ;# MAC type
set val(ifq)            Queue/DropTail/PriQueue    ;# interface queue type
set val(ll)             LL                         ;# link layer type
set val(ant)            Antenna/OmniAntenna        ;# antenna model
set val(ifqlen)         50                         ;# max packet in ifq
set val(nn)             50                         ;# number of mobilenodes
set val(rp)             AODV                       ;# routing protocol
set opt(cp) "cbr-50n-10c-2p";					   ;# use the cbr file generated by cbrgen.tcl
set opt(sc) "scene-50n-0p-20M-300t-1000-300";	   ;# use the scence file generated by setdest


#===============================
# Main Program
#===============================

#Create a simulator object
set ns_ [new Simulator]

#Open the trace file
set tracefd [open aodv.tr w]
$ns_ trace-all $tracefd
$ns_ use-newtrace

#Open the nam file
set namtracefd [open aodv.nam w]
$ns_ namtrace-all-wireless $namtracefd 1000 300

#set the simulation topography
set topo [new Topography]
$topo load_flatgrid 1000 300
set god_ [new God]
create-god $val(nn)

# configure the network
$ns_ node-config -adhocRouting $val(rp) \
-llType $val(ll) \
-macType $val(mac) \
-ifqType $val(ifq) \
-ifqLen $val(ifqlen) \
-antType $val(ant) \
-propType $val(prop) \
-phyType $val(netif) \
-channelType $val(chan) \
-topoInstance $topo \
-agentTrace ON \
-routerTrace ON \
-macTrace OFF \
-movementTrace OFF \

#Create mobilenodes with number of val(nn)
for {set i 0} {$i<$val(nn)} {incr i} {
	set node_($i) [$ns_ node]
	$node_($i) random-motion 0
}

#Use the cbr file and scence file
source $opt(cp)
source $opt(sc)

#Schedule envents for simualtion
for {set i 0} {$i<$val(nn)} {incr i} {
	$ns_ at 300.1 "$node_($i) reset";
}
$ns_ at 300.2 "stop"
$ns_ at 300.3 "puts \"NS EXITING...\"; $ns_ halt"

#Define a 'finish' or 'stop' procedure
proc stop {} {
	#record the simalation process to trace and nam file
	global ns_ tracefd namtracefd
	$ns_ flush-trace

	#Close the trace file
	close $tracefd

	#Close the nam file
	close $namtracefd

	#Execute NAM on the nam file
	exec nam aodv.nam &
	exit 0
}

#Run the simulation
$ns_ run
