version: '3'
services:
  ns2:
    build: .
    image: ns2
    container_name: ns2
    environment:
      - DISPLAY=docker.for.mac.localhost:0
    ports:
      - "8080:8080"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../ns-2.35:/ns2/ns-2.35
      - ../notebook:/notebook
    restart: always
    command: jupyter notebook
    privileged: true
