version: '3'
services:
  ns2:
    build: .
    image: ns2
    container_name: ns2
    environment:
      - DISPLAY=docker.for.mac.localhost:0
    ports:
      - "8080:8080"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../ns-2.35:/ns2/ns-2.35
      - ../py-parser:/app/py-parser
      - ../tools:/app/tools
      - ../notebook:/notebook
      - ./init/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    restart: always
    command: jupyter lab
    privileged: true
